# Generated by Django 3.1.3 on 2020-11-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='contents',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
